version: "3.8"

services:
  db:
    image: mysql:8
    container_name: anime90s-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime90s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: anime90s-backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: anime90s
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: anime90s-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app   # Live reload

volumes:
  db_data:
